sudo: required
dist: bionic
language: node_js
node_js:
    - '12'

before_install:
    - git fetch origin master:master

install:
    - set -e
    - yarn

script:
    - set -e
    - yarn test

git:
  depth: false
deploy:
    - provider: script
      script: "git checkout master && yarn publish:canary && yarn build:containers:canary"
      skip_cleanup: true
      on:
        node: "12"
        branch: master
    - provider: script
      script: "git checkout release && yarn publish:release && yarn build:containers:release"
      skip_cleanup: true
      on:
        node: "12"
        branch: release
        condition: $TRAVIS_COMMIT_MESSAGE =~ ^((?!skip-deploy).)*$